version: 1.0.{build}
image: Visual Studio 2013
platform: x64
configuration: Release
clone_depth: 1
environment:
  matrix:
    - PACKAGE: 'AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations '
    - PACKAGE: 'Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres '
    - PACKAGE: 'Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 '
    - PACKAGE: 'Arithmetic_kernel Arrangement_on_surface_2 Barycentric_coordinates_2 '
    - PACKAGE: 'BGL Boolean_set_operations_2 Bounding_volumes '
    - PACKAGE: 'Box_intersection_d Cartesian_kernel CGAL_Core '
    - PACKAGE: 'CGAL_ImageIO CGAL_ipelets Circular_kernel_2 '
    - PACKAGE: 'Circular_kernel_3 Circulator Classification '
    - PACKAGE: 'Combinatorial_map Cone_spanners_2 Convex_decomposition_3 '
    - PACKAGE: 'Convex_hull_2 Convex_hull_3 Convex_hull_d '
    - PACKAGE: 'Distance_2 Distance_3 Envelope_2 '
    - PACKAGE: 'Envelope_3 Filtered_kernel Generalized_map '
    - PACKAGE: 'Generator Geomview GraphicsView '
    - PACKAGE: 'HalfedgeDS Hash_map Homogeneous_kernel '
    - PACKAGE: 'Inscribed_areas Installation Interpolation '
    - PACKAGE: 'Intersections_2 Intersections_3 Interval_skip_list '
    - PACKAGE: 'Interval_support Inventor Jet_fitting_3 '
    - PACKAGE: 'Kernel_23 Kernel_d Kinetic_data_structures '
    - PACKAGE: 'Kinetic_framework LEDA Linear_cell_complex '
    - PACKAGE: 'MacOSX Maintenance Matrix_search '
    - PACKAGE: 'Mesh_2 Mesh_3 Mesher_level '
    - PACKAGE: 'Minkowski_sum_2 Minkowski_sum_3 Modifier '
    - PACKAGE: 'Modular_arithmetic Nef_2 Nef_3 '
    - PACKAGE: 'Nef_S2 NewKernel_d Number_types '
    - PACKAGE: 'OpenNL Operations_on_polyhedra Optimal_transportation_reconstruction_2 '
    - PACKAGE: 'Optimisation_basic Partition_2 Periodic_2_triangulation_2 '
    - PACKAGE: 'Periodic_3_triangulation_3 Point_set_2 Point_set_3 '
    - PACKAGE: 'Point_set_processing_3 Point_set_shape_detection_3 Poisson_surface_reconstruction_3 '
    - PACKAGE: 'Polygon Polygon_mesh_processing Polyhedron '
    - PACKAGE: 'Polyhedron_IO Polyline_simplification_2 Polynomial '
    - PACKAGE: 'Polytope_distance_d Principal_component_analysis Principal_component_analysis_LGPL '
    - PACKAGE: 'Profiling_tools Property_map QP_solver '
    - PACKAGE: 'Random_numbers Ridges_3 Scale_space_reconstruction_3 '
    - PACKAGE: 'Scripts SearchStructures Segment_Delaunay_graph_2 '
    - PACKAGE: 'Segment_Delaunay_graph_Linf_2 Set_movable_separability_2 Skin_surface_3 '
    - PACKAGE: 'Snap_rounding_2 Solver_interface Spatial_searching '
    - PACKAGE: 'Spatial_sorting STL_Extension Straight_skeleton_2 '
    - PACKAGE: 'Stream_lines_2 Stream_support Subdivision_method_3 '
    - PACKAGE: 'Surface_mesh Surface_mesh_deformation Surface_mesher '
    - PACKAGE: 'Surface_mesh_parameterization Surface_mesh_segmentation Surface_mesh_shortest_path '
    - PACKAGE: 'Surface_mesh_simplification Surface_mesh_skeletonization Surface_sweep_2 '
    - PACKAGE: 'TDS_2 TDS_3 Testsuite '
    - PACKAGE: 'Three Triangulation Triangulation_2 '
    - PACKAGE: 'Triangulation_3 Union_find Visibility_2 '
    - PACKAGE: 'Voronoi_diagram_2 wininst '
    - PACKAGE: 'Polyhedron_demo'

##Only for qglviewer
#init:
#  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%
install:
    -  set "CONDA_ROOT=C:\Miniconda36-x64"
    -  set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;;C:\Qt\5.6\msvc2013_64\bin;%PATH%"
    -  set "BOOST_ROOT=C:\Libraries/boost"
    -  conda install -y -c conda-forge cmake
    -  conda install -y -c anaconda-nb-extensions gmp
    -  conda install -y -c conda-forge mpfr
    -  conda install -y -c conda-forge zlib
    -  conda install -y -c conda-forge eigen

before_build:
- cmd:
- cd C:\projects\cgal\ && mkdir build && cd build && cmake -DCGAL_HEADER_ONLY=ON -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG .. && cmake --build . && cmake --build . --target install

build_script:
- cd C:\projects\cgal\.travis
- C:\Cygwin\bin\bash.exe -x -e build_package.sh 1 %PACKAGE%
