version: 1.0.{build}
image: Visual Studio 2013
build_script:
- cmd: echo "Hello world."
install:
-  set "CONDA_ROOT=C:\Miniconda36-x64"
-  set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
-  conda install -y -c conda-forge cmake 
-  conda install -y -c anaconda-nb-extensions gmp 
-  conda install -y -c conda-forge mpfr
-  conda install -y -c conda-forge zlib   
test: off
