# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: "ubuntu-16.04"

variables:
  buildConfiguration: 'Release'
  BUILD_DIR: $(Agent.BuildDirectory)
  SOURCE_DIR: $(Build.SourcesDirectory)
  
strategy:
  matrix:
    AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations  :
      PACKAGE: AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations
    Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres  :
      PACKAGE: Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres
    Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2  :
      PACKAGE: Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2
    Arrangement_on_surface_2  :
      PACKAGE: Arrangement_on_surface_2
    Arithmetic_kernel  BGL  :
      PACKAGE: Arithmetic_kernel BGL
    Barycentric_coordinates_2 Boolean_set_operations_2 Bounding_volumes  :
      PACKAGE: Barycentric_coordinates_2 Boolean_set_operations_2 Bounding_volumes
    Box_intersection_d CGAL_Core CGAL_ImageIO  :
      PACKAGE: Box_intersection_d CGAL_Core CGAL_ImageIO
    CGAL_ipelets Cartesian_kernel Circular_kernel_2  :
      PACKAGE: CGAL_ipelets Cartesian_kernel Circular_kernel_2
    Circular_kernel_3 Circulator Classification  :
      PACKAGE: Circular_kernel_3 Circulator Classification
    Combinatorial_map Cone_spanners_2 Convex_decomposition_3  :
      PACKAGE: Combinatorial_map Cone_spanners_2 Convex_decomposition_3
    Convex_hull_2 Convex_hull_3 Convex_hull_d  :
      PACKAGE: Convex_hull_2 Convex_hull_3 Convex_hull_d
    Distance_2 Distance_3 Envelope_2  :
      PACKAGE: Distance_2 Distance_3 Envelope_2
    Envelope_3 Filtered_kernel Generalized_map  :
      PACKAGE: Envelope_3 Filtered_kernel Generalized_map
    Generator Geomview GraphicsView  :
      PACKAGE: Generator Geomview GraphicsView
    HalfedgeDS Hash_map Heat_method_3  :
      PACKAGE: HalfedgeDS Hash_map Heat_method_3
    Homogeneous_kernel Hyperbolic_triangulation_2 Inscribed_areas  :
      PACKAGE: Homogeneous_kernel Hyperbolic_triangulation_2 Inscribed_areas
    Installation Interpolation Intersections_2  :
      PACKAGE: Installation Interpolation Intersections_2
    Intersections_3 Interval_skip_list Interval_support  :
      PACKAGE: Intersections_3 Interval_skip_list Interval_support
    Inventor Jet_fitting_3 Kernel_23  :
      PACKAGE: Inventor Jet_fitting_3 Kernel_23
    Kernel_d LEDA Linear_cell_complex  :
      PACKAGE: Kernel_d LEDA Linear_cell_complex
    MacOSX Maintenance Matrix_search  :
      PACKAGE: MacOSX Maintenance Matrix_search
    Mesh_3  :
      PACKAGE: Mesh_3
    Mesh_2 Mesher_level  :
      PACKAGE: Mesh_2 Mesher_level
    Minkowski_sum_2 Minkowski_sum_3 Modifier  :
      PACKAGE: Minkowski_sum_2 Minkowski_sum_3 Modifier
    Modular_arithmetic Nef_2 Nef_3  :
      PACKAGE: Modular_arithmetic Nef_2 Nef_3
    Nef_S2 NewKernel_d Number_types  :
      PACKAGE: Nef_S2 NewKernel_d Number_types
    OpenNL Optimal_transportation_reconstruction_2 Optimisation_basic  :
      PACKAGE: OpenNL Optimal_transportation_reconstruction_2 Optimisation_basic
    Partition_2 Periodic_2_triangulation_2 Periodic_3_mesh_3  :
      PACKAGE: Partition_2 Periodic_2_triangulation_2 Periodic_3_mesh_3
    Periodic_3_triangulation_3 Periodic_4_hyperbolic_triangulation_2 Point_set_2  :
      PACKAGE: Periodic_3_triangulation_3 Periodic_4_hyperbolic_triangulation_2 Point_set_2
    Point_set_3 Point_set_processing_3 Poisson_surface_reconstruction_3  :
      PACKAGE: Point_set_3 Point_set_processing_3 Poisson_surface_reconstruction_3
    Polygon Polygon_mesh_processing Polygonal_surface_reconstruction  :
      PACKAGE: Polygon Polygon_mesh_processing Polygonal_surface_reconstruction
    Polyhedron Polyhedron_IO Polyline_simplification_2  :
      PACKAGE: Polyhedron Polyhedron_IO Polyline_simplification_2
    Polynomial Polytope_distance_d Principal_component_analysis  :
      PACKAGE: Polynomial Polytope_distance_d Principal_component_analysis
    Principal_component_analysis_LGPL Profiling_tools Property_map  :
      PACKAGE: Principal_component_analysis_LGPL Profiling_tools Property_map
    QP_solver Random_numbers Ridges_3  :
      PACKAGE: QP_solver Random_numbers Ridges_3
    STL_Extension Scale_space_reconstruction_3 Scripts  :
      PACKAGE: STL_Extension Scale_space_reconstruction_3 Scripts
    SearchStructures Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2  :
      PACKAGE: SearchStructures Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2
    Set_movable_separability_2 Shape_detection Skin_surface_3  :
      PACKAGE: Set_movable_separability_2 Shape_detection Skin_surface_3
    Snap_rounding_2 Solver_interface Spatial_searching  :
      PACKAGE: Snap_rounding_2 Solver_interface Spatial_searching
    Spatial_sorting Straight_skeleton_2 Stream_lines_2  :
      PACKAGE: Spatial_sorting Straight_skeleton_2 Stream_lines_2
    Stream_support Subdivision_method_3 Surface_mesh  :
      PACKAGE: Stream_support Subdivision_method_3 Surface_mesh
    Surface_mesh_approximation Surface_mesh_deformation Surface_mesh_parameterization  :
      PACKAGE: Surface_mesh_approximation Surface_mesh_deformation Surface_mesh_parameterization
    Surface_mesh_segmentation Surface_mesh_shortest_path Surface_mesh_simplification  :
      PACKAGE: Surface_mesh_segmentation Surface_mesh_shortest_path Surface_mesh_simplification
    Surface_mesh_skeletonization Surface_mesher Surface_sweep_2  :
      PACKAGE: Surface_mesh_skeletonization Surface_mesher Surface_sweep_2
    TDS_2 TDS_3 Testsuite  :
      PACKAGE: TDS_2 TDS_3 Testsuite
    Triangulation  :
      PACKAGE: Triangulation
    Three Union_find Visibility_2  :
      PACKAGE: Three Union_find Visibility_2
    Voronoi_diagram_2  :
      PACKAGE: Voronoi_diagram_2

steps:
  
- script: |
    sudo apt install -yq --no-install-suggests --no-install-recommends --force-yes clang zsh flex bison cmake graphviz libgmp-dev libmpfr-dev libmpfi-dev zlib1g-dev libeigen3-dev  libboost-dev libboost-system-dev libboost-program-options-dev libboost-thread-dev libboost-iostreams-dev qtbase5-dev libqt5sql5-sqlite libqt5opengl5-dev qtscript5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools qml-module-qtgraphicaleffects libopencv-dev mesa-common-dev libmetis-dev libglu1-mesa-dev
  displayName: Install CGAL Dependencies

- checkout: self
  fetchDepth: 1

- bash: |
    cd $BUILD_DIR
    cmake  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DWITH_tests=ON -DWITH_examples=ON -DCMAKE_CXX_FLAGS_RELEASE='-Wall -frounding-math' $SOURCE_DIR
    INIT=""
    NO_PARALLEL=""
    for pkg in ${PACKAGE}; do
      if [ pkg == "Kernel_23" ]; then
        NO_PARALLEL="true"
      fi
      if [ -z "$INIT" ]; then
        TO_TEST=$pkg
        INIT="y"
      else
        TO_TEST="${TO_TEST}|$pkg"
      fi
    done
    if [ -z $NO_PARALLEL ]; then
      ctest -L ${TO_TEST} -E execution___of__ -VV
    else
      ctest -j2 -L ${TO_TEST} -E execution___of__ -VV
    fi
  displayName: Test
  env:
    name: Linux
    

