# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: "vs2017-win2016"

variables:
  buildConfiguration: 'Release'
  BUILD_DIR: $(Agent.BuildDirectory)
  SOURCE_DIR: $(Build.SourcesDirectory)
  
strategy:
  matrix:
    AABB_tree:
      PACKAGE: AABB_tree  
    Advancing_front_surface_reconstruction  :
      PACKAGE: Advancing_front_surface_reconstruction  
    Algebraic_foundations  :
      PACKAGE: Algebraic_foundations  
    Algebraic_kernel_d  :
      PACKAGE: Algebraic_kernel_d  
    Algebraic_kernel_for_circles  :
      PACKAGE: Algebraic_kernel_for_circles  
    Algebraic_kernel_for_spheres  :
      PACKAGE: Algebraic_kernel_for_spheres  
    Alpha_shapes_2  :
      PACKAGE: Alpha_shapes_2  
    Alpha_shapes_3  :
      PACKAGE: Alpha_shapes_3  
    Apollonius_graph_2  :
      PACKAGE: Apollonius_graph_2  
    Arithmetic_kernel  :
      PACKAGE: Arithmetic_kernel  
    Arrangement_on_surface_2  :
      PACKAGE: Arrangement_on_surface_2  
    Barycentric_coordinates_2  :
      PACKAGE: Barycentric_coordinates_2  
    BGL  :
      PACKAGE: BGL  
    Boolean_set_operations_2  :
      PACKAGE: Boolean_set_operations_2  
    Bounding_volumes  :
      PACKAGE: Bounding_volumes  
    Box_intersection_d  :
      PACKAGE: Box_intersection_d  
    Cartesian_kernel  :
      PACKAGE: Cartesian_kernel  
    CGAL_Core  :
      PACKAGE: CGAL_Core  
    CGAL_ImageIO  :
      PACKAGE: CGAL_ImageIO  
    CGAL_ipelets  :
      PACKAGE: CGAL_ipelets  
    Circular_kernel_2  :
      PACKAGE: Circular_kernel_2  
    Circular_kernel_3  :
      PACKAGE: Circular_kernel_3  
    Circulator  :
      PACKAGE: Circulator  
    Classification  :
      PACKAGE: Classification  
    Combinatorial_map  :
      PACKAGE: Combinatorial_map  
    Cone_spanners_2  :
      PACKAGE: Cone_spanners_2  
    Convex_decomposition_3  :
      PACKAGE: Convex_decomposition_3  
    Convex_hull_2  :
      PACKAGE: Convex_hull_2  
    Convex_hull_3  :
      PACKAGE: Convex_hull_3  
    Convex_hull_d  :
      PACKAGE: Convex_hull_d  
    Distance_2  :
      PACKAGE: Distance_2  
    Distance_3  :
      PACKAGE: Distance_3  
    Envelope_2  :
      PACKAGE: Envelope_2  
    Envelope_3  :
      PACKAGE: Envelope_3  
    Filtered_kernel  :
      PACKAGE: Filtered_kernel  
    Generalized_map  :
      PACKAGE: Generalized_map  
    Generator  :
      PACKAGE: Generator  
    Geomview  :
      PACKAGE: Geomview  
    GraphicsView  :
      PACKAGE: GraphicsView  
    HalfedgeDS  :
      PACKAGE: HalfedgeDS  
    Hash_map  :
      PACKAGE: Hash_map  
    Heat_method_3  :
      PACKAGE: Heat_method_3  
    Homogeneous_kernel  :
      PACKAGE: Homogeneous_kernel  
    Hyperbolic_triangulation_2  :
      PACKAGE: Hyperbolic_triangulation_2  
    Inscribed_areas  :
      PACKAGE: Inscribed_areas  
    Installation  :
      PACKAGE: Installation  
    Interpolation  :
      PACKAGE: Interpolation  
    Intersections_2  :
      PACKAGE: Intersections_2  
    Intersections_3  :
      PACKAGE: Intersections_3  
    Interval_skip_list  :
      PACKAGE: Interval_skip_list  
    Interval_support  :
      PACKAGE: Interval_support  
    Inventor  :
      PACKAGE: Inventor  
    Jet_fitting_3  :
      PACKAGE: Jet_fitting_3  
    Kernel_23  :
      PACKAGE: Kernel_23  
    Kernel_d  :
      PACKAGE: Kernel_d  
    LEDA  :
      PACKAGE: LEDA  
    Linear_cell_complex  :
      PACKAGE: Linear_cell_complex  
    MacOSX  :
      PACKAGE: MacOSX  
    Maintenance  :
      PACKAGE: Maintenance  
    Matrix_search  :
      PACKAGE: Matrix_search  
    Mesh_2  :
      PACKAGE: Mesh_2  
    Mesh_3  :
      PACKAGE: Mesh_3  
    Mesher_level  :
      PACKAGE: Mesher_level  
    Minkowski_sum_2  :
      PACKAGE: Minkowski_sum_2  
    Minkowski_sum_3  :
      PACKAGE: Minkowski_sum_3  
    Modifier  :
      PACKAGE: Modifier  
    Modular_arithmetic  :
      PACKAGE: Modular_arithmetic  
    Nef_2  :
      PACKAGE: Nef_2  
    Nef_3  :
      PACKAGE: Nef_3  
    Nef_S2  :
      PACKAGE: Nef_S2  
    NewKernel_d  :
      PACKAGE: NewKernel_d  
    Number_types  :
      PACKAGE: Number_types  
    OpenNL  :
      PACKAGE: OpenNL  
    Optimal_transportation_reconstruction_2  :
      PACKAGE: Optimal_transportation_reconstruction_2  
    Optimisation_basic  :
      PACKAGE: Optimisation_basic  
    Partition_2  :
      PACKAGE: Partition_2  
    Periodic_2_triangulation_2  :
      PACKAGE: Periodic_2_triangulation_2  
    Periodic_3_mesh_3  :
      PACKAGE: Periodic_3_mesh_3  
    Periodic_3_triangulation_3  :
      PACKAGE: Periodic_3_triangulation_3  
    Periodic_4_hyperbolic_triangulation_2  :
      PACKAGE: Periodic_4_hyperbolic_triangulation_2  
    Point_set_2  :
      PACKAGE: Point_set_2  
    Point_set_3  :
      PACKAGE: Point_set_3  
    Point_set_processing_3  :
      PACKAGE: Point_set_processing_3  
    Point_set_shape_detection_3  :
      PACKAGE: Point_set_shape_detection_3  
    Poisson_surface_reconstruction_3  :
      PACKAGE: Poisson_surface_reconstruction_3  
    Polygon  :
      PACKAGE: Polygon  
    Polygon_mesh_processing  :
      PACKAGE: Polygon_mesh_processing  
    Polyhedron  :
      PACKAGE: Polyhedron  
    Polyhedron_IO  :
      PACKAGE: Polyhedron_IO  
    Polyline_simplification_2  :
      PACKAGE: Polyline_simplification_2  
    Polynomial  :
      PACKAGE: Polynomial  
    Polytope_distance_d  :
      PACKAGE: Polytope_distance_d  
    Principal_component_analysis  :
      PACKAGE: Principal_component_analysis  
    Principal_component_analysis_LGPL  :
      PACKAGE: Principal_component_analysis_LGPL  
    Profiling_tools  :
      PACKAGE: Profiling_tools  
    Property_map  :
      PACKAGE: Property_map  
    QP_solver  :
      PACKAGE: QP_solver  
    Random_numbers  :
      PACKAGE: Random_numbers  
    Ridges_3  :
      PACKAGE: Ridges_3  
    Scale_space_reconstruction_3  :
      PACKAGE: Scale_space_reconstruction_3  
    Scripts  :
      PACKAGE: Scripts  
    SearchStructures  :
      PACKAGE: SearchStructures  
    Segment_Delaunay_graph_2  :
      PACKAGE: Segment_Delaunay_graph_2  
    Segment_Delaunay_graph_Linf_2  :
      PACKAGE: Segment_Delaunay_graph_Linf_2  
    Set_movable_separability_2  :
      PACKAGE: Set_movable_separability_2  
    Skin_surface_3  :
      PACKAGE: Skin_surface_3  
    Snap_rounding_2  :
      PACKAGE: Snap_rounding_2  
    Solver_interface  :
      PACKAGE: Solver_interface  
    Spatial_searching  :
      PACKAGE: Spatial_searching  
    Spatial_sorting  :
      PACKAGE: Spatial_sorting  
    STL_Extension  :
      PACKAGE: STL_Extension  
    Straight_skeleton_2  :
      PACKAGE: Straight_skeleton_2  
    Stream_lines_2  :
      PACKAGE: Stream_lines_2  
    Stream_support  :
      PACKAGE: Stream_support  
    Subdivision_method_3  :
      PACKAGE: Subdivision_method_3  
    Surface_mesh  :
      PACKAGE: Surface_mesh  
    Surface_mesh_approximation  :
      PACKAGE: Surface_mesh_approximation  
    Surface_mesh_deformation  :
      PACKAGE: Surface_mesh_deformation  
    Surface_mesher  :
      PACKAGE: Surface_mesher  
    Surface_mesh_parameterization  :
      PACKAGE: Surface_mesh_parameterization  
    Surface_mesh_segmentation  :
      PACKAGE: Surface_mesh_segmentation  
    Surface_mesh_shortest_path  :
      PACKAGE: Surface_mesh_shortest_path  
    Surface_mesh_simplification  :
      PACKAGE: Surface_mesh_simplification  
    Surface_mesh_skeletonization  :
      PACKAGE: Surface_mesh_skeletonization  
    Surface_sweep_2  :
      PACKAGE: Surface_sweep_2  
    TDS_2  :
      PACKAGE: TDS_2  
    TDS_3  :
      PACKAGE: TDS_3  
    Testsuite  :
      PACKAGE: Testsuite  
    Three  :
      PACKAGE: Three  
    Triangulation  :
      PACKAGE: Triangulation  
    Triangulation_2  :
      PACKAGE: Triangulation_2  
    Triangulation_3  :
      PACKAGE: Triangulation_3  
    Union_find  :
      PACKAGE: Union_find  
    Visibility_2  :
      PACKAGE: Visibility_2  
    Voronoi_diagram_2  :
      PACKAGE: Voronoi_diagram_2  
    wininst  :
      PACKAGE: wininst  

 

steps:
- powershell: |
    Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH
- checkout: self
  fetchDepth: 1

- script: |
   conda install -y -c conda-forge cgal --only-deps
  displayName: Install Dependencies


- bash: |
    cd $BUILD_DIR && cmake  -G "Visual Studio 15 2017 Win64" -DBoost_DEBUG=1 -DBUILD_TESTING=ON -DWITH_tests=ON -DWITH_examples=ON -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG -DCMAKE_PREFIX_PATH="C:\Miniconda\Library" $SOURCE_DIR  && ctest --build-config "Release" -L $(PACKAGE)
  displayName: Test
  env:
    name: Microsoft
    

