name: Documentation

on: [pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.0.0
    - name: install dependencies
      run: |
         set -x
         sudo apt-get install -y graphviz ssh rsync
         sudo pip install lxml pyquery
         wget -O doxygen_exe https://cgal.geometryfactory.com/~mgimeno/doxygen/build_1_8_13/bin/doxygen
         sudo mv doxygen_exe /usr/bin/doxygen
         sudo chmod +x /usr/bin/doxygen
         mkdir -p ~/.ssh
         (
         cat <<EOF
         ${{ secrets.ssh_key }}
         EOF
         )>> ~/.ssh/id_rsa
         chmod 600 /home/runner/.ssh/id_rsa 
         (
         cat <<EOF
         ${{ secrets.ssh_key_pub }}
         EOF
         )>> ~/.ssh/id_rsa.pub
         chmod 644 /home/runner/.ssh/id_rsa.pub
         (
         cat <<EOF
         github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
         EOF
         )>> ~/.ssh/known_hosts
         git config --global user.email "maxime.gimeno@geometryfactory.com"
         git config --global user.name "Maxime Gimeno"
         
    - name: configure all
      run: |
        git clone git@github.com:CGAL/cgal.github.io.git
        mkdir build_doc && cd build_doc && cmake ../Documentation/doc
    - name: Upload Doc
      run: |
        set -e
        PR_NUMBER=$(python -c "import json; import os; y = json.load(open(os.environ['GITHUB_EVENT_PATH'])); print(y[\"number\"])")
        mkdir cgal.github.io/${PR_NUMBER}
        cd build_doc && make -j2 doc && make -j2 doc_with_postprocessing
        mv ./doc_output/* ../cgal.github.io/${PR_NUMBER}/
        #rsync --compress -a doc_output/* ${{ secrets.ids }}/cgal.github.io/${PR_NUMBER}/
        cd ../cgal.github.io && git add ${PR_NUMBER} && git commit -a -m "Add ${PR_NUMBER}" && git push -u origin master
        #ssh mgimeno@cgal.geometryfactory.com "cd /home/mgimeno/public_html/cgal.github.io && git add ${PR_NUMBER} && git commit -a -m 'Add a new directory' && git push origin master"
