name: Documentation

on:
  pull_request_target:
    types: [opened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: TEST
      run: |
        if $(cat $GITHUB_EVENT_PATH | jq '.pull_request.labels | contains(["small feature"])'); then
          echo " Build doc."
        else
          echo "Don't build doc."
        fi
