name: Documentation

on: pull_request_target
    types: closed
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: delete directory
      run: |
         mkdir -p ~/.ssh
         (
         cat <<EOF
         ${{ secrets.ssh_key }}
         EOF
         )>> ~/.ssh/id_rsa
         chmod 600 /home/runner/.ssh/id_rsa 
         (
         cat <<EOF
         ${{ secrets.ssh_key_pub }}
         EOF
         )>> ~/.ssh/id_rsa.pub
         chmod 644 /home/runner/.ssh/id_rsa.pub
         (
         cat <<EOF
         cgal.geometryfactory.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJcYFTViwMpkUHPWqM1Cvf6hD3t3kV//QPenMwLzvFMa
         |1|GMIJAmFHn7K7IaG3Uie0MfEo8sM=|2fzc+UO3J2GnlaV+0Mqc4I+mbXo= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
         EOF
         )>> ~/.ssh/known_hosts
         
        ssh ${{ secrets.ids }}/pr_doc/ rm -rf ${PR_NUMBER}/
    
