name: Filter Testsuite

on:
  issue_comment:
      types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: check
        with:
         result-encoding: string
         script: |
           const userName = context.payload.comment.user.login
           if(userName == 'maxGimeno') {
             const body = context.payload.comment.body
             if(body.includes("run filter test")) {
               return 'OK'
             }
           }
           return 'stop'

      - name: Run Testsuite
        if: steps.check.outputs.result != 'stop'
        run: |
          ssh mgimeno@geometryfactory.pro.dns-orange.fr 'touch coucou.txt'
