name: Filter Testsuite

on:
  issue_comment:
      types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: check
        with:
         result-encoding: string
         script: |
           const userName = context.payload.comment.user.login
           if(userName == 'maxGimeno') {
             const body = context.payload.comment.body
             if(body.includes("/testme")) {             
               return 'OK'
             }
           }
           return 'stop'
      - uses: actions/github-script@v3
        if: steps.check.result != 'stop'
        id: get_label
        with:
         result-encoding: string
         script: |
           //get branch name and username
           const pr_url = context.payload.issue.pull_request.url
           const pr_content = await github.request(pr_url)
           const label = pr_content.data.head.label
           console.log(label)
           return label
      - uses: actions/github-script@v3
        if: steps.check.result != 'stop'
        id: get_base
        with:
         result-encoding: string
         script: |
           //get branch name and username   
           const pr_url = context.payload.issue.pull_request.url
           const pr_content = await github.request(pr_url)
           const base = pr_content.data.base.ref
           console.log(base)
           return base
      - name: Run Testsuite
        if: steps.check.outputs.result != 'stop'
        run: |
          mkdir -p ~/.ssh
          #ssh key
          (
          cat <<EOF
          ${{ secrets.ssh_key }}
          EOF
          )>> ~/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa 
          #ssh public key
          (
          cat <<EOF
          ${{ secrets.ssh_key_pub }}
          EOF
          )>> ~/.ssh/id_rsa.pub
          chmod 644 /home/runner/.ssh/id_rsa.pub
          #known hosts
          wget --no-check-certificate https://cgal.geometryfactory.com/CGAL/ssh_known_hosts -O ~/.ssh/known_hosts
          #config file
          wget --no-check-certificate https://cgal.geometryfactory.com/CGAL/ssh_config -O ~/.ssh/config 
          #list of hosts
          wget --no-check-certificate https://cgal.geometryfactory.com/CGAL/ssh_host_list -O ~/ssh_host_list
          #ssh command
          LABEL="${{ steps.get_label.outputs.result }}"
          USER_NAME=$(echo $LABEL | cut -d':' -f 1)
          BRANCH_NAME=$(echo $LABEL | cut -d':' -f 2)
          BASE="${{ steps.get_base.outputs.result }}"
          mapfile -t HOSTS < ~/ssh_host_list;
          LAST_INDEX=$((${#HOSTS[@]}-1))
          for i in ${!HOSTS[@]}; do
            HOST=$(echo ${HOSTS[$i]}|cut -d' ' -f 1 )
            PATH_TO_SCRIPT=$(echo ${HOSTS[$i]}|cut -d' ' -f 2 )
            if [ "$i" -ne  "$LAST_INDEX" ] ; then
              ssh ${HOST} "${PATH_TO_SCRIPT}/run_testsuite_from_branch_name.sh $USER_NAME $BRANCH_NAME $BASE"
            else
              ssh ${HOST} "${PATH_TO_SCRIPT}/run_testsuite_from_branch_name.sh $USER_NAME $BRANCH_NAME $BASE y"
            fi
          done
      - name: Post address
        uses: actions/github-script@v3
        if: steps.check.outputs.result != 'stop'
        with:
          script: |
            const address = "The testsuite is lauched. results will be found, after it is done, here : https://cgal.geometryfactory.com/~mgimeno/test_suite/TESTRESULTS/index.shtml "
            github.issues.createComment({
              owner: "maxGimeno",
              repo: "cgal",
              issue_number: ${{ github.event.issue.number }},
              body: address
            });
